In [1]:
import numpy as np
import pylab as pl

In [2]:
import pandas as pd
df=pd.read_csv("test.csv",sep=",")
df

X (s)    Y (m/s2)
0     0.000000  -38.137400
1     0.000195  -18.454800
2     0.000391    0.524003
3     0.000586  -41.132300
4     0.000781  -24.442400
5     0.000977   -6.831800
6     0.001172  -36.661300
7     0.001367  -88.690800
8     0.001563  -94.817300
9     0.001758  -51.658400
10    0.001953  -47.689100
11    0.002148  -58.704000
12    0.002344  -47.027800
13    0.002539   -6.052350
14    0.002734   10.250100
15    0.002930   13.593500
16    0.003125    5.425620
17    0.003320   -6.407630
18    0.003516    0.166957
19    0.003711    0.256114
20    0.003906   -2.026900
21    0.004102   -8.463640
22    0.004297   38.005600
23    0.004492   70.737400
24    0.004687   49.960400
25    0.004883   27.171200
26    0.005078   10.153000
27    0.005273   34.737100
28    0.005469   28.445000
29    0.005664   12.864300
...        ...         ...
2018  0.394141   90.122200
2019  0.394336   37.901400
2020  0.394531   40.797900
2021  0.394727  -56.318700
2022  0.394922  -42.931900
2023  0.395117   85.152100
2024  0.395313   52.798000
2025  0.395508    9.274460
2026  0.395703   15.712000
2027  0.395898   -8.339500
2028  0.396094  -17.972100
2029  0.396289  -26.288300
2030  0.396484   10.842800
2031  0.396680   -6.332280
2032  0.396875  -35.739700
2033  0.397070  -21.192900
2034  0.397266  -81.759200
2035  0.397461 -104.772000
2036  0.397656 -104.595000
2037  0.397852  -92.697900
2038  0.398047  -31.840600
2039  0.398242  -70.875700
2040  0.398438  -63.040700
2041  0.398633  -40.737300
2042  0.398828  -54.743400
2043  0.399023   19.035900
2044  0.399219   54.087100
2045  0.399414   17.018200
2046  0.399609    6.186720
2047  0.399805    7.698710

[2048 rows x 2 columns]

In [3]:
df['X (s)']

0       0.000000
1       0.000195
2       0.000391
3       0.000586
4       0.000781
5       0.000977
6       0.001172
7       0.001367
8       0.001563
9       0.001758
10      0.001953
11      0.002148
12      0.002344
13      0.002539
14      0.002734
15      0.002930
16      0.003125
17      0.003320
18      0.003516
19      0.003711
20      0.003906
21      0.004102
22      0.004297
23      0.004492
24      0.004687
25      0.004883
26      0.005078
27      0.005273
28      0.005469
29      0.005664
          ...   
2018    0.394141
2019    0.394336
2020    0.394531
2021    0.394727
2022    0.394922
2023    0.395117
2024    0.395313
2025    0.395508
2026    0.395703
2027    0.395898
2028    0.396094
2029    0.396289
2030    0.396484
2031    0.396680
2032    0.396875
2033    0.397070
2034    0.397266
2035    0.397461
2036    0.397656
2037    0.397852
2038    0.398047
2039    0.398242
2040    0.398438
2041    0.398633
2042    0.398828
2043    0.399023
2044    0.399219
2045    0.3994

In [4]:
x=np.array(df['X (s)'])
x

array([  0.00000000e+00,   1.95313000e-04,   3.90625000e-04, ...,
         3.99414000e-01,   3.99609000e-01,   3.99805000e-01])

In [5]:
y=np.array(df['Y (m/s2)'])
y

array([-38.1374  , -18.4548  ,   0.524003, ...,  17.0182  ,   6.18672 ,
         7.69871 ])

In [6]:
def FFT(x,y,T):
    N=len(y)
    n=N/2
    df=1/T
    PSD=np.zeros(n)
    C=np.zeros(n)
    S=np.zeros(n)
    for i in range (0,n,1):
        for j in range (0,N,1):
            if i==0:
                C[i] += y[j]
            else:
                C[i] += np.cos(2*np.pi*(i/T)*x[j])*y[j]
                S[i] += np.sin(2*np.pi*(i/T)*x[j])*y[j]     
        if i==0:
            C[i]=C[i]/N
            PSD[i]= C[i]**2/df
            print "i=",i,C[i],PSD[i]
        else:
            C[i]= 2.0/N *C[i]
            S[i]= 2.0/N *S[i]
            PSD[i]= 0.5*((C[i]**2+S[i]**2)/df)
            print "i=",i,C[i],S[i],PSD[i]
    f=np.arange(0,n*df,df)
    pl.figure () 
    pl.plot(f,PSD)
    pl.xlabel('Hz')
    pl.ylabel('PSD')
    pl.show()
    return PSD,f

In [7]:
PSD,f=FFT(x,y,0.4)

i= 0 -0.285666870264 0.0326422243065
i= 1 -0.440631047048 0.00302935242334 0.0388329793198
i= 2 -0.442166347001 0.00134304195057 0.0391025764363
i= 3 -0.453282144342 0.0142242443229 0.0411334063012
i= 4 -0.45487015943 0.0176406010419 0.041443610549
i= 5 -0.462384040435 0.0310782753949 0.04295297201
i= 6 -0.485434812621 0.0238823832961 0.0472434651073
i= 7 -0.486356535126 0.0157177702854 0.0473579455125
i= 8 -0.47676081831 -0.00918143512478 0.0454770353254
i= 9 -0.0878923748366 -0.440573393503 0.0403659969235
i= 10 -2.4385997867 0.0960223638855 1.19119784282
i= 11 -0.968877721577 -0.0357469483935 0.188000376738
i= 12 -2.4019683295 1.4317134983 1.56385107943
i= 13 0.130752797419 -1.64226662207 0.542827190401
i= 14 1.29564983745 1.15173671326 0.601041191593
i= 15 -1.3615491048 -1.71708569036 0.960439846564
i= 16 2.9186068556 -5.84836144983 8.54431952507
i= 17 -2.07527427549 -1.55221680967 1.34322806855
i= 18 5.48798114101 -6.89086766587 15.5203988385
i= 19 -2.52841786781 -4.45705806512 5.

In [8]:
PSD

array([  3.26422243e-02,   3.88329793e-02,   3.91025764e-02, ...,
         1.62614733e-04,   8.46583607e-06,   1.48433837e-04])

In [9]:
f

array([  0.00000000e+00,   2.50000000e+00,   5.00000000e+00, ...,
         2.55250000e+03,   2.55500000e+03,   2.55750000e+03])

In [10]:
len(f)

1024

In [11]:
yf  =  np . fft . fft ( y ) 
yf

array([-585.04575030 +0.j        , -451.20119457 -3.09735602j,
       -452.80104859 -1.37438984j, ..., -464.17243956+14.56565052j,
       -452.80104859 +1.37438984j, -451.20119457 +3.09735602j])

In [12]:
yf=abs(yf)*2/2048
yf

array([ 0.57133374,  0.44063655,  0.44219056, ...,  0.45351652,
        0.44219056,  0.44063655])

In [13]:
f=np.arange(0,2048*2.5,2.5)
f

array([  0.00000000e+00,   2.50000000e+00,   5.00000000e+00, ...,
         5.11250000e+03,   5.11500000e+03,   5.11750000e+03])

In [14]:
df['yf']=yf
df['f']=f

In [15]:
df2=df[:801]
df2

X (s)    Y (m/s2)         yf       f
0    0.000000  -38.137400   0.571334     0.0
1    0.000195  -18.454800   0.440637     2.5
2    0.000391    0.524003   0.442191     5.0
3    0.000586  -41.132300   0.453517     7.5
4    0.000781  -24.442400   0.455195    10.0
5    0.000977   -6.831800   0.463459    12.5
6    0.001172  -36.661300   0.486009    15.0
7    0.001367  -88.690800   0.486648    17.5
8    0.001563  -94.817300   0.476873    20.0
9    0.001758  -51.658400   0.449257    22.5
10   0.001953  -47.689100   2.440477    25.0
11   0.002148  -58.704000   0.969501    27.5
12   0.002344  -47.027800   2.796302    30.0
13   0.002539   -6.052350   1.647492    32.5
14   0.002734   10.250100   1.733577    35.0
15   0.002930   13.593500   2.191279    37.5
16   0.003125    5.425620   6.536276    40.0
17   0.003320   -6.407630   2.591630    42.5
18   0.003516    0.166957   8.809144    45.0
19   0.003711    0.256114   5.124202    47.5
20   0.003906   -2.026900   3.515662    50.0
21   0.004102   -8.463640  10.981424    52.5
22   0.004297   38.005600  10.798493    55.0
23   0.004492   70.737400   0.412316    57.5
24   0.004687   49.960400   2.105058    60.0
25   0.004883   27.171200   2.370174    62.5
26   0.005078   10.153000   3.351815    65.0
27   0.005273   34.737100   9.475280    67.5
28   0.005469   28.445000   1.983209    70.0
29   0.005664   12.864300   2.811592    72.5
..        ...         ...        ...     ...
771  0.150586  -22.433100   1.139794  1927.5
772  0.150781   10.879200   1.475681  1930.0
773  0.150977   20.878600   1.471425  1932.5
774  0.151172   16.996600   1.961444  1935.0
775  0.151367  -26.290000   0.797042  1937.5
776  0.151563  -12.457300   0.525674  1940.0
777  0.151758   61.735900   0.378814  1942.5
778  0.151953   30.491000   2.883654  1945.0
779  0.152148  -11.543700   2.646099  1947.5
780  0.152344   10.112400   1.004377  1950.0
781  0.152539    6.348690   1.637234  1952.5
782  0.152734   31.087500   0.297093  1955.0
783  0.152930   53.283800   1.182740  1957.5
784  0.153125   61.600900   0.520072  1960.0
785  0.153320   45.418400   0.561649  1962.5
786  0.153516   23.285700   1.809804  1965.0
787  0.153711   99.318800   1.164909  1967.5
788  0.153906   91.123900   2.053422  1970.0
789  0.154102   29.205000   1.609660  1972.5
790  0.154297   67.299900   2.234320  1975.0
791  0.154492   47.211300   0.730428  1977.5
792  0.154688   66.245100   0.601354  1980.0
793  0.154883  132.495000   1.150529  1982.5
794  0.155078   57.185700   2.213194  1985.0
795  0.155273   30.058900   1.165627  1987.5
796  0.155469   83.216400   1.198395  1990.0
797  0.155664   73.487500   0.628767  1992.5
798  0.155859   95.608900   1.989992  1995.0
799  0.156055   97.974000   1.021469  1997.5
800  0.156250   53.644800   1.483265  2000.0

[801 rows x 4 columns]

In [16]:
df2['PSD']=PSD[:801]
df2

C:\Users\user\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


X (s)    Y (m/s2)         yf       f        PSD
0    0.000000  -38.137400   0.571334     0.0   0.032642
1    0.000195  -18.454800   0.440637     2.5   0.038833
2    0.000391    0.524003   0.442191     5.0   0.039103
3    0.000586  -41.132300   0.453517     7.5   0.041133
4    0.000781  -24.442400   0.455195    10.0   0.041444
5    0.000977   -6.831800   0.463459    12.5   0.042953
6    0.001172  -36.661300   0.486009    15.0   0.047243
7    0.001367  -88.690800   0.486648    17.5   0.047358
8    0.001563  -94.817300   0.476873    20.0   0.045477
9    0.001758  -51.658400   0.449257    22.5   0.040366
10   0.001953  -47.689100   2.440477    25.0   1.191198
11   0.002148  -58.704000   0.969501    27.5   0.188000
12   0.002344  -47.027800   2.796302    30.0   1.563851
13   0.002539   -6.052350   1.647492    32.5   0.542827
14   0.002734   10.250100   1.733577    35.0   0.601041
15   0.002930   13.593500   2.191279    37.5   0.960440
16   0.003125    5.425620   6.536276    40.0   8.544320
17   0.003320   -6.407630   2.591630    42.5   1.343228
18   0.003516    0.166957   8.809144    45.0  15.520399
19   0.003711    0.256114   5.124202    47.5   5.251653
20   0.003906   -2.026900   3.515662    50.0   2.472090
21   0.004102   -8.463640  10.981424    52.5  24.118208
22   0.004297   38.005600  10.798493    55.0  23.321822
23   0.004492   70.737400   0.412316    57.5   0.034005
24   0.004687   49.960400   2.105058    60.0   0.886327
25   0.004883   27.171200   2.370174    62.5   1.123516
26   0.005078   10.153000   3.351815    65.0   2.247044
27   0.005273   34.737100   9.475280    67.5  17.956529
28   0.005469   28.445000   1.983209    70.0   0.786719
29   0.005664   12.864300   2.811592    72.5   1.581075
..        ...         ...        ...     ...        ...
771  0.150586  -22.433100   1.139794  1927.5   0.258602
772  0.150781   10.879200   1.475681  1930.0   0.434806
773  0.150977   20.878600   1.471425  1932.5   0.430686
774  0.151172   16.996600   1.961444  1935.0   0.769170
775  0.151367  -26.290000   0.797042  1937.5   0.127034
776  0.151563  -12.457300   0.525674  1940.0   0.055865
777  0.151758   61.735900   0.378814  1942.5   0.028015
778  0.151953   30.491000   2.883654  1945.0   1.652716
779  0.152148  -11.543700   2.646099  1947.5   1.399045
780  0.152344   10.112400   1.004377  1950.0   0.204570
781  0.152539    6.348690   1.637234  1952.5   0.535361
782  0.152734   31.087500   0.297093  1955.0   0.017499
783  0.152930   53.283800   1.182740  1957.5   0.280392
784  0.153125   61.600900   0.520072  1960.0   0.055262
785  0.153320   45.418400   0.561649  1962.5   0.062302
786  0.153516   23.285700   1.809804  1965.0   0.649321
787  0.153711   99.318800   1.164909  1967.5   0.267460
788  0.153906   91.123900   2.053422  1970.0   0.837055
789  0.154102   29.205000   1.609660  1972.5   0.521651
790  0.154297   67.299900   2.234320  1975.0   0.996956
791  0.154492   47.211300   0.730428  1977.5   0.107102
792  0.154688   66.245100   0.601354  1980.0   0.071016
793  0.154883  132.495000   1.150529  1982.5   0.264975
794  0.155078   57.185700   2.213194  1985.0   0.974924
795  0.155273   30.058900   1.165627  1987.5   0.275512
796  0.155469   83.216400   1.198395  1990.0   0.284581
797  0.155664   73.487500   0.628767  1992.5   0.081713
798  0.155859   95.608900   1.989992  1995.0   0.783756
799  0.156055   97.974000   1.021469  1997.5   0.207103
800  0.156250   53.644800   1.483265  2000.0   0.443463

[801 rows x 5 columns]

In [38]:
PSD2=np.zeros(801)
for i in range (0,801,1):
    if i==0 or i==800:
        PSD2[i]=yf[i]**2/2.5/4
    else:
        PSD2[i]=yf[i]**2/2.5/2
PSD2

array([  3.26422243e-02,   3.88321136e-02,   3.91064984e-02,
         4.11354469e-02,   4.14404789e-02,   4.29588843e-02,
         4.72410019e-02,   4.73653283e-02,   4.54815839e-02,
         4.03664135e-02,   1.19118549e+00,   1.87986360e-01,
         1.56386134e+00,   5.42846291e-01,   6.01057638e-01,
         9.60340898e-01,   8.54458123e+00,   1.34330940e+00,
         1.55202040e+01,   5.25148900e+00,   2.47197567e+00,
         2.41183345e+01,   2.33214897e+01,   3.40008394e-02,
         8.86253685e-01,   1.12354450e+00,   2.24693221e+00,
         1.79561858e+01,   7.86623287e-01,   1.58100987e+00,
         1.68550135e+01,   3.27859961e+01,   1.24177057e+01,
         2.83273292e+01,   5.00556165e+00,   2.11657278e+01,
         5.04074750e-01,   7.81695600e-01,   3.53832854e+01,
         5.59909612e+00,   6.07937740e+00,   1.66577983e+01,
         3.74835150e+00,   1.37693061e+01,   7.40997902e+00,
         1.10479631e+01,   8.79336992e-01,   1.05424104e+01,
         4.57635836e+00,

In [39]:
len(PSD2)

801

In [40]:
df2['PSD2']=PSD2

C:\Users\user\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [41]:
df2

X (s)    Y (m/s2)         yf       f        PSD       PSD2
0    0.000000  -38.137400   0.571334     0.0   0.032642   0.032642
1    0.000195  -18.454800   0.440637     2.5   0.038833   0.038832
2    0.000391    0.524003   0.442191     5.0   0.039103   0.039106
3    0.000586  -41.132300   0.453517     7.5   0.041133   0.041135
4    0.000781  -24.442400   0.455195    10.0   0.041444   0.041440
5    0.000977   -6.831800   0.463459    12.5   0.042953   0.042959
6    0.001172  -36.661300   0.486009    15.0   0.047243   0.047241
7    0.001367  -88.690800   0.486648    17.5   0.047358   0.047365
8    0.001563  -94.817300   0.476873    20.0   0.045477   0.045482
9    0.001758  -51.658400   0.449257    22.5   0.040366   0.040366
10   0.001953  -47.689100   2.440477    25.0   1.191198   1.191185
11   0.002148  -58.704000   0.969501    27.5   0.188000   0.187986
12   0.002344  -47.027800   2.796302    30.0   1.563851   1.563861
13   0.002539   -6.052350   1.647492    32.5   0.542827   0.542846
14   0.002734   10.250100   1.733577    35.0   0.601041   0.601058
15   0.002930   13.593500   2.191279    37.5   0.960440   0.960341
16   0.003125    5.425620   6.536276    40.0   8.544320   8.544581
17   0.003320   -6.407630   2.591630    42.5   1.343228   1.343309
18   0.003516    0.166957   8.809144    45.0  15.520399  15.520204
19   0.003711    0.256114   5.124202    47.5   5.251653   5.251489
20   0.003906   -2.026900   3.515662    50.0   2.472090   2.471976
21   0.004102   -8.463640  10.981424    52.5  24.118208  24.118335
22   0.004297   38.005600  10.798493    55.0  23.321822  23.321490
23   0.004492   70.737400   0.412316    57.5   0.034005   0.034001
24   0.004687   49.960400   2.105058    60.0   0.886327   0.886254
25   0.004883   27.171200   2.370174    62.5   1.123516   1.123544
26   0.005078   10.153000   3.351815    65.0   2.247044   2.246932
27   0.005273   34.737100   9.475280    67.5  17.956529  17.956186
28   0.005469   28.445000   1.983209    70.0   0.786719   0.786623
29   0.005664   12.864300   2.811592    72.5   1.581075   1.581010
..        ...         ...        ...     ...        ...        ...
771  0.150586  -22.433100   1.139794  1927.5   0.258602   0.259826
772  0.150781   10.879200   1.475681  1930.0   0.434806   0.435527
773  0.150977   20.878600   1.471425  1932.5   0.430686   0.433019
774  0.151172   16.996600   1.961444  1935.0   0.769170   0.769452
775  0.151367  -26.290000   0.797042  1937.5   0.127034   0.127055
776  0.151563  -12.457300   0.525674  1940.0   0.055865   0.055267
777  0.151758   61.735900   0.378814  1942.5   0.028015   0.028700
778  0.151953   30.491000   2.883654  1945.0   1.652716   1.663092
779  0.152148  -11.543700   2.646099  1947.5   1.399045   1.400368
780  0.152344   10.112400   1.004377  1950.0   0.204570   0.201754
781  0.152539    6.348690   1.637234  1952.5   0.535361   0.536107
782  0.152734   31.087500   0.297093  1955.0   0.017499   0.017653
783  0.152930   53.283800   1.182740  1957.5   0.280392   0.279775
784  0.153125   61.600900   0.520072  1960.0   0.055262   0.054095
785  0.153320   45.418400   0.561649  1962.5   0.062302   0.063090
786  0.153516   23.285700   1.809804  1965.0   0.649321   0.655078
787  0.153711   99.318800   1.164909  1967.5   0.267460   0.271403
788  0.153906   91.123900   2.053422  1970.0   0.837055   0.843308
789  0.154102   29.205000   1.609660  1972.5   0.521651   0.518201
790  0.154297   67.299900   2.234320  1975.0   0.996956   0.998437
791  0.154492   47.211300   0.730428  1977.5   0.107102   0.106705
792  0.154688   66.245100   0.601354  1980.0   0.071016   0.072325
793  0.154883  132.495000   1.150529  1982.5   0.264975   0.264743
794  0.155078   57.185700   2.213194  1985.0   0.974924   0.979646
795  0.155273   30.058900   1.165627  1987.5   0.275512   0.271737
796  0.155469   83.216400   1.198395  1990.0   0.284581   0.287230
797  0.155664   73.487500   0.628767  1992.5   0.081713   0.079070
798  0.155859   95.608900   1.989992  1995.0   0.783756

In [42]:
pl.figure () 
pl.plot(f[:801],PSD[:801])
pl.xlabel('Hz')
pl.xscale('log')
pl.ylabel('PSD')
pl.yscale('log')
pl.xlim(24,2000)
pl.ylim(0, 100)
pl.grid(True, linestyle = "-.", color = "r", linewidth = "3", which='major')
pl.show()