In [11]:
import numpy as np
import pylab as pl

In [12]:
y=np.array([1.0, 2.0, 0.0, -1.0, -3.0, -2.0, 1.0, -1.0])
x=np.array([0,0.5/1000,1.0/1000,1.5/1000,2.0/1000,2.5/1000,3.0/1000,3.5/1000])

In [13]:
def FFT(x,y,T):
    N=len(y)
    n=N/2
    df=1/T
    PSD=np.zeros(4)
    C=np.zeros(4)
    S=np.zeros(4)
    for i in range (0,4,1):
        for j in range (0,8,1):
            if i==0:
                C[i] += y[j]
            else:
                C[i] += np.cos(2*np.pi*(i/T)*x[j])*y[j]
                S[i] += np.sin(2*np.pi*(i/T)*x[j])*y[j]     
        if i==0:
            C[i]=C[i]/N
            PSD[i]= C[i]**2/df
            print "i=",i,C[i],PSD[i]
        else:
            C[i]= 2.0/N *C[i]
            S[i]= 2.0/N *S[i]
            PSD[i]= 0.5*((C[i]**2+S[i]**2)/df)
            print "i=",i,C[i],S[i],PSD[i]
    f=np.arange(0,n*df,df)
    pl.figure () 
    pl.plot(f,PSD)
    pl.xlabel('Hz')
    pl.ylabel('PSD')
    pl.show()
    return PSD

In [14]:
PSD=FFT(x,y,4.0/1000)

i= 0 -0.375 0.0005625
i= 1 1.70710678119 0.457106781187 0.00624632034356
i= 2 -0.75 0.5 0.001625
i= 3 0.292893218813 0.957106781187 0.00200367965644


In [15]:
PSD

array([ 0.0005625 ,  0.00624632,  0.001625  ,  0.00200368])

In [16]:
yf  =  np . fft . fft ( y ) 

In [17]:
PSD2=(abs(yf)*2/8)
PSD2

array([ 0.75      ,  1.76724649,  0.90138782,  1.00091949,  0.25      ,
        1.00091949,  0.90138782,  1.76724649])

In [18]:
PSD2[0]=PSD2[0]**2/4/250
PSD[0]

0.00056249999999999996

In [19]:
PSD2[1]=PSD2[1]**2/2/250
PSD2[2]=PSD2[2]**2/2/250
PSD2[3]=PSD2[3]**2/2/250
PSD2

array([  5.62500000e-04,   6.24632034e-03,   1.62500000e-03,
         2.00367966e-03,   2.50000000e-01,   1.00091949e+00,
         9.01387819e-01,   1.76724649e+00])

In [22]:
PSD2[:4]

array([ 0.0005625 ,  0.00624632,  0.001625  ,  0.00200368])